### ISSUE TITLE
Support plugin auto hide

### ISSUE THREAD

**Issue by PeiyuanQi** [lxieyang/vertical-tabs-chrome-extension#27]
It will be great if the tool could have the option to auto-hide when not active and appears when mouse hovers on the edge of the browser.

**Comment by lxieyang** [comment]
Ok! What do you want the closing behavior to be? If you hover over and the sidebar appears, do you want it closed when you leave it for a while automatically or you need to click a button/use the keyboard shortcut to close it explicitly?

**Comment by PeiyuanQi** [comment]
> do you want it closed when you leave it for a while automatically or you need to click a button/use the keyboard shortcut to close it explicitly?

Yes, if there is an option in setting i.g. "Auto Hide: Yes / No"
In Yes:
Once my mouse leaves the sidebar for 1 second, the sidebar hides, the sidebar reappears when the mouse is hovering on the edge of the browser.
This is to address some reviews that say this sidebar is still taking too much space on the screen.
In No:
The sidebar does what it does now.

**Comment by lxieyang** [comment]
Cool! Will consider adding this feature as suggested when I find some time over the coming weeks! Thanks for the suggestion!

**Comment by quique123** [comment]
Doesnt work properly.  Cmd+E should show, but it doesnt always work.  If Im on a google.com tab then Cmd+E works fine and shows the left tab but if im on some other tab, Cmd+E does nothing.

Also it doesnt automatically hide after 300ms after being off the sidebar.  My mouse pointer is on this window and has been since i started typing and the left side bar hasnt auto-hidden.
