### ISSUE TITLE
Vertical tabs disappear when I click '+' (Add tab) or go to Chrome Settings page

### ISSUE THREAD

**Issue by JetsonDavis** [lxieyang/vertical-tabs-chrome-extension#30]
Here's a video:

https://www.dropbox.com/s/qrpudv7dhgy0n5w/Vertical%20Tabs%20Issue.mov?dl=0

**Comment by lxieyang** [comment]
Hi, thanks for the interest!

TBH, as much as I want them to work, this is something that Chrome prevents us developers to do. Essentially, what the extension currently is doing is injecting an iframe to the webpages that you're browsing through something called `content_script`. However, since new tabs and any of the chrome pages like the settings page are considered a part of the Chrome UI and therefore not regular webpages, no chrome extension are allowed to interfere with them, let alone injecting something into them (even if in our case it's something completely benign). So, unless Google/Chrome in the future decides otherwise, there's currently no way of showing the vertical tabs on new tabs and the settings page.

That said, I hope the following can help ease your concern:
- I created this extension as a hobby project so that you could quickly access different webpages from other webpages through a sidebar (I'm a little obsessed with sidebars of those control dashboards and alike). In the future, I could imagine a feature where you're also able to click the extension icon, and the vertical list will show in a popup.
- I heard that MS Edge is considering adding this vertical tabs feature into their UI. I imagine unlike Chrome, Edge will add this as a native browser UI, so that you can access the list independent of which page you have open. That might be another good thing to look forward to (honestly, I'm pretty excited about that too!)

Hope this helps! And thanks again for your interest and trying this extension out!

**Comment by JetsonDavis** [comment]
Hey Michael,

Thank you for the detailed explanation!  I use Firefox with Tree Style Tab which works incredibly well.  I want to switch to Chrome because of some dev tools unavailable on FF, but am dependent on vertical tabs!  Guess I’ll stay put for now.

Best,

Jeff

**Comment by lxieyang** [comment]
I know! I personally also use FF just for it's Tree Style Tabs.
